version: "3"
services:
    node:
        restart: always
        build: .
        ports:
            - 80:5000
        volumes:
            - ./:/code
    mongo:
        image: mongo
        ports:
            - 27018:27017
        volumes:
            - mongodb:/data/db
volumes:
    mongodb:
